### ISSUE TITLE
File types

### ISSUE THREAD

**Issue by maol3** [helmutschneider/swish-php#14]
I seem to only get CSR, KEY and PEM/P7B-files according to Swish manual.
How do I use these files with your application? Is there any tutorial out how I can convert them to the right file formats?

Thanks in advance!

**Comment by helmutschneider** [comment]
Instructions are provided in the [readme](https://github.com/helmutschneider/swish-php#obtaining-test-certificates). As a general rule you want to use PEM-encoded files because that's what cURL supports.
