### ISSUE TITLE
Php 8.1 and Guzzle 8

### ISSUE THREAD

**Issue by oakleaf** [helmutschneider/swish-php#21]
Hello, how far away are we from supporting Php 8.1 and Guzzle version more than 7?

**Comment by dhedberg** [comment]
I have tagged 3.0.1 with some updated dependencies, does that solve the issue you were seeing?

The version will probably not be visible on packagist for a while since the auto-update is not enabled.

**Comment by oakleaf** [comment]
Great! Except the support for Php 8+

E.g:
    "require": {
        "php": "^7.2|^8.0"

Is that something you can add?

**Comment by dhedberg** [comment]
I did add >=7.3 in 3.0.1 and tested it with php 8.0 and 8.1, so I think it should work.

3.0.1 is active on packagist now as well, not sure when that was updated though.

Does it not work for you?

**Comment by oakleaf** [comment]
Yes it seems to work! Great and many thanks! :)
