### ISSUE TITLE
possible to pay to my customers/consumers ?

### ISSUE THREAD

**Issue by Govind13100** [helmutschneider/swish-php#3]
In Swish API , is this possible to pay to users/customers/consumers who ever visit my site, login and ready to sell their products/items. 

Please let me know if this possible and how i could achieve this???

Thanks in advance !!!

**Comment by jarnheimer** [comment]
If the customer has the Swish app and BankID you can @Govind13100 
Read more on this page https://www.getswish.se/handel/

**Comment by Govind13100** [comment]
I want B2C payment in this api, is this possible????

**Comment by helmutschneider** [comment]
Sorry, I am not responsible for the features available in the Swish API. Refer to https://www.getswish.se/ or contact your local bank.
