### ISSUE TITLE
Empty return on callback

### ISSUE THREAD

**Issue by maol3** [helmutschneider/swish-php#4]
When I'm performing the payment request my browser prints "NULL" while I get the payment request in my Swish app.

However when the payment is done, Swish returns an empty _POST-array in the callback. I've logged it to database and this is what it returns: https://gyazo.com/ed84a84205992626295d514028791fad

What could be the issue? Thanks in advance!

**Comment by maol3** [comment]
Just to make it clear, I've logged serialize($_POST) to the payment_reference column. It's completely empty.

**Comment by helmutschneider** [comment]
I'm fairly certain swish posts the callback data in JSON. You'll have to decode it manually:
```php
$data = file_get_contents('php://input');
$decoded = json_decode($data, $assoc = true);

// do something with the json array
var_dump($decoded);
```
